name: number_paginated_list
description: "A Flutter paginated list package"
version: 1.0.2
homepage: https://github.com/RichardM20/number_paginated
repository: https://github.com/RichardM20/number_paginated

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  number_paginator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - paginator
  - widget
  - number-paginator
  - paginated
  - paginated-list

screenshots:
  - description: 'DemoVideoPreview'
    path: screenshots/demo.gif
  - description: 'NumberPaginated.listView'
    path: screenshots/paginated_list_view.png
  - description: 'NumberPaginated.gridView'
    path: screenshots/paginated_list_grid.png
