name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest
    if: needs.deploy-for-web.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        id: publish
        run: flutter pub publish --force --no-prepublish
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
