name: Publish Package

on:
  workflow_run:
    workflows: ["Build Web"]
    types:
      - completed

jobs:
  publish-package:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter pub publish --force --no-prepublish
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
